from pathlib import Path
import json
import re
import warnings

import numpy as np
import pandas as pd

import single_neuron_1 as step1
import single_neuron_2 as step2


warnings.filterwarnings("ignore")
seed = 42
np.random.seed(seed)


base_path = Path("/home/dilettabartolini/neural-adaptation-adex-triplet-stdp")
results_path = base_path / "Results_DE_optimization"

# Threshold parameters used to create a dedicated output folder in z_score.
threshold_high = 2
threshold_low = 1
min_stimuli = 3

# Pattern used to select only folders generated by the optimization pipeline.
pattern_folder = re.compile(r"alpha[0-9.]+_beta[0-9.]+_eps[0-9.]+_seed\d+_\d+$")      


def build_output_paths():
    # Create and return all output folders for the selected threshold combination.

    # Build the output folder name from the selected threshold values.
    output_subfolder = f"Thr{threshold_high}_thr{min_stimuli}_{threshold_low}"

    # Define the main output folder and the two subfolders used by the z-score step.
    output_path = base_path / "Z_score" / output_subfolder
    raw_score_path = output_path / "Raw_score"
    filtered_score_path = output_path / "Filtered_score"

    # Create all required folders if they do not already exist.
    for path in (output_path, raw_score_path, filtered_score_path):
        path.mkdir(parents=True, exist_ok=True)

    return {
        "output_subfolder": output_subfolder,
        "output_path": output_path,
        "raw_score_path": raw_score_path,
        "filtered_score_path": filtered_score_path,
    }


def build_delta_tables(delta_data):
    # Create detailed and summary delta tables using the fixed mad-based classification.

    # Convert the collected delta results into a dataframe.
    delta_df = pd.DataFrame(delta_data)

    if delta_df.empty:
        raise ValueError("delta_data is empty. Cannot build delta tables.")

    # Calculate classification thresholds and labels from the delta distribution.
    (
        left_threshold,
        right_threshold,
        _mad_delta,
        delta_tolerance,
        _mode_name,
        type_names,
    ) = step1.calculate_classification_params(delta_df)
    # Assign a neuron type to each delta value.
    delta_df["type"] = delta_df["delta"].apply(
        lambda value: step1.classify_delta(
            value,
            left_threshold,
            right_threshold,
            type_names,
        )
    )

    summary_rows = []

    # Build one summary row for each configuration folder.
    for folder in delta_df["folder"].unique():
        folder_data = delta_df[delta_df["folder"] == folder]

        # Store summary statistics for all active neurons in the current folder.
        row = {
            "folder": folder,
            "total_neurons": len(folder_data),
            "mean_delta": folder_data["delta"].mean(),
            "std_delta": folder_data["delta"].std(),
            "median_delta": folder_data["delta"].median(),
            "q1_delta": folder_data["delta"].quantile(0.25),
            "q3_delta": folder_data["delta"].quantile(0.75),
            "mean_responsive_stimuli": folder_data[
                "n_responsive_stimuli"
            ].mean(),
        }

        # Count how many neurons belong to each classification label.
        for label in (
            type_names["left"],
            type_names["middle"],
            type_names["right"],
        ):
            if label is not None:
                row[f"n_{label}"] = int((folder_data["type"] == label).sum())

        summary_rows.append(row)

    # Convert the configuration-level summary into a dataframe.
    summary_df = pd.DataFrame(summary_rows)

    return summary_df, delta_tolerance, type_names


def run_analysis():
    # Run the full analysis workflow:
    # z-score filtering, delta classification, cluster merging, table generation, and figure generation.

    # Create and collect all output paths.
    paths = build_output_paths()
    output_path = paths["output_path"]
    raw_score_path = paths["raw_score_path"]
    filtered_score_path = paths["filtered_score_path"]

    # Load all raw z-score tables from the optimization results.
    all_raw_data, _ = step1.load_raw_data(
        results_path,
        pattern_folder,
    )

    if not all_raw_data:
        raise SystemExit("no valid data found. exiting.")

    # Apply the two z-score filters and collect active neurons and delta values.
    (
        _file_count,
        _filtered_count,
        _total_filtered_neurons,
        delta_data,
        active_neurons_dict,
    ) = step1.process_data(
        all_raw_data,
        raw_score_path,
        filtered_score_path,
        threshold_high,
        threshold_low,
        min_stimuli,
    )

    # Save the active-neuron ids for each configuration.
    active_neurons_path = output_path / "active_neurons_per_config.json"

    with open(active_neurons_path, "w", encoding="utf-8") as file:
        json.dump(active_neurons_dict, file, indent=2)

    if not delta_data:
        raise SystemExit("no delta data found after filtering. exiting.")

    # Build detailed and summary delta tables.
    delta_summary_df, _delta_tolerance, type_names = build_delta_tables(delta_data)

    step2.test_normality(values=delta_summary_df["mean_delta"], save_dir=output_path, name="mean_delta")
    
    # Create the cluster summary from step_4 results.
    df_cluster = step2.create_cluster_summary(results_path)

    # Rename the folder column so that it matches the cluster dataframe key.
    df_delta = delta_summary_df.rename(columns={"folder": "config_name"})

    # Merge cluster-level and delta-level information.
    df_merged = step2.merge_data(df_cluster, df_delta)

    if df_merged is None or df_merged.empty:
        raise SystemExit("no common configurations found. exiting.")

    # Classify configurations using the majority-count rule.
    df_classified = step2.prepare_data_for_analysis(
        df_merged,
        type_names=type_names,
    )
        
    # Export clean final Excel phenotype table, including none and tie configurations.
    step2.export_table(
        df=df_classified,
        save_dir=output_path,
        filename="Phenotypes.xlsx",
        phenotype_col="type",
    )

    # Generate the tables
    step2.generate_tables(
        df=df_classified,
        type_col="type",
        save_dir=output_path,
    )

    # Generate the 3d comparison figure.
    step2.plot_3d_comparison(
        df=df_classified,
        type_col="type",
        save_dir=output_path,
        method_name="Two_Types",
    )

    # Generate the side-by-side parameter and duration figure.
    step2.create_side_by_side_figure(
        df_filtered=df_classified,
        save_dir=output_path,
        method_name="two_types",
        type_col="type",
    )

if __name__ == "__main__":
    run_analysis()
